# Generated by Django 3.0.3 on 2020-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20200208_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('r', 'red'), ('y', 'yellow'), ('g', 'green')], default='r', max_length=20),
        ),
    ]
